GCC := gcc
FLAGS := -std=c99 -Wall -Werror -D EXPORTS -ggdb
OBJF := func_lib.o

%.o : %.c *.h
	$(GCC) $(FLAGS) -c $<

func.dll : func_lib.o
	$(GCC) -shared func_lib.o -Wl,--subsystem,windows -o func.dll

test.exe : $(OBJF) test.o
	$(GCC) $^ -L. $(LIBF) -o $@

clean :
	rm *.o *dll