CC := gcc
CFLAGS := -std=c99 -Wall -Werror -pedantic
OBJS := read_list.o push.o pop.o sort.o append.o output.o

main.exe : $(OBJS) main.o
	$(CC) $(CFLAGS) $^ -o main.exe

test.exe : $(OBJS) test.o
	$(CC) $(CFLAGS) $^ -o test.exe

%.o : %.c *.h
	$(CC) $(CFLAGS) -c $<

clean :
	$(RM) $(CLEAR)
