CC := gcc
CFLAGS := -std=c99 -Wall -Werror -pedantic
OBJS := list.o file_funcs.o

main.exe : $(OBJS) main.o
	$(CC) $(CFLAGS) $^ -o main.exe

test.exe : $(OBJS) test.o
	$(CC) $(CFLAGS) $^ -o test.exe

%.o : %.c *.h
	$(CC) $(CFLAGS) -c $<

clean :
	$(RM) $(CLEAR)
